- hosts: all
  tasks:
    - name: Set up apt repos
      apt_repository: repo='{{ item }}' state=present
      with_items:
        - deb http://archive.ubuntu.com/ubuntu trusty main
        - deb http://archive.ubuntu.com/ubuntu trusty-security main

    - name: Install packages
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - postgresql
        - python
        - python-dev
        - python3-dev
        - python3-pip
        - python-psycopg2

    - name: Remove Python 2 virtualenv
      apt: name=python-virtualenv state=absent

    - name: install pip
      pip: executable=pip3 name=pip state=latest

    - name: install python 3 virtualenv
      pip: executable=pip3 name=virtualenv state=latest

    - name: Remove home dir venv from ssh env
      lineinfile: dest=/home/vagrant/.bashrc regexp='~/bapi-venv/bin/activate' state=absent

    - name: Set up initial ssh env
      lineinfile: dest=/home/vagrant/.bashrc line='source /vagrant/venv/bin/activate; cd /vagrant/'

    - name: set up postgresql user
      postgresql_user: name=vagrant role_attr_flags=CREATEDB
      sudo_user: postgres
      notify:
        - Set up database
        - Open postgres to listen
        - Trust incoming psql connections
        - start postgresql and configure to startup automatically

  handlers:
    - name: Set up database
      postgresql_db: name=pyconomy owner=vagrant
      sudo_user: postgres

    - name: Open postgres to listen
      lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf line="listen_addresses = '*'"

    - name: Trust incoming psql connections
      lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf line='host all all 10.0.2.2/32 trust'

    - name: start postgresql and configure to startup automatically
      service: name=postgresql state=started enabled=yes
      register: started
      tags: postgresql
